### PR TITLE
Close display window only if OpenAfterRender is set

### PR DESCRIPTION
**Pull request by howetuft**

### CODE REVIEW

**Comment by Francisco-Rosa** [comment]
howetuft,

I preferred to answer here because of the length of the subject.


I left it that way because for now it is only possible to record with the "Open After Render" position set to "True". If not enabled, it displays the following error:...
      rpv.runRecordCamera()
...RecordPlayVideo.py", line 337, in runRecordCamera
     shutil.move(output_file, f"" + CL.R2_3FrameOutputPath +'/' + frameFinalName)
   File "/tmp/.mount_FreeCAFjm9gy/usr/lib/python3.10/shutil.py", line 815, in move
     os.rename(src, real_dst)

rename: src should be string, bytes or os.PathLike, not NoneType

As I understand it, if you don't open the file in FC after rendering, this will not generate the temporary file that "shutil" moves to the desired location.

In Blender, the default option is to save the images or the video in a temporary folder, but the user can change it to a folder of his choice (but in this case, I didn't check if he keeps the files in the temporary one too, for security reasons).

 In FC, from what I've noticed, the temporary render files are replaced it at each render, so they are loosed any way. I don't know how to do it and if this is inconvenient or complicate, but allows the render to be saved directly in the configured location instead of the temporary one, it could be a possibility too and this would allow leaving 'False' to open after the render, I believe.
Would a render batch folder help?

In case we don't change anything, I believe it would be better to have a warning for the user to leave the True position, in case he has changed it to false. What do you think?

    Em terça-feira, 27 de dezembro de 2022 06:41:10 BRT, howetuft ***@***.***> escreveu:  
 
 
You can view, comment on, or merge this pull request online at:

  https://github.com/Francisco-Rosa/FreeCAD-Movie/pull/4

Commit Summary
   
   - 5397a68 Close display window only if OpenAfterRender is set

File Changes 
 
(1 file)
   
   -  M RecordPlayVideo.py (3) 

Patch Links:
   
   - https://github.com/Francisco-Rosa/FreeCAD-Movie/pull/4.patch
   - https://github.com/Francisco-Rosa/FreeCAD-Movie/pull/4.diff

**Comment by howetuft** [comment]
> As I understand it, if you don't open the file in FC after rendering, this will not generate the temporary file that "shutil" moves to the desired location.

Well, not really. The file was duly generated, but the filename was not returned by `Project.render` method. But it was a *bug* of course. I've fixed it and pushed to `movie` branch.
Problem is I mixed the patch with a few other updates enabling batch mode for all renderers.
So I'm gonna terminate my on-going work and notice you when I am finished, so that you can merge.

> In Blender, the default option is to save the images or the video in a temporary folder, but the user can change it to a folder of his choice

This is the same in Render: you can specify the destination file, this is the `Output Image` parameter of the `Project`. If you specify this file and you change it from one rendering to another, you won't overwrite.

**Comment by Francisco-Rosa** [comment]
howetuft,

Understood, and thanks for the feedback. As for saving via output, I couldn't use it, would it not be the case of using PropertyPath instead of PropertyFile?
F_Rosa.

    Em terça-feira, 27 de dezembro de 2022 12:31:22 BRT, howetuft ***@***.***> escreveu:  
 
 



As I understand it, if you don't open the file in FC after rendering, this will not generate the temporary file that "shutil" moves to the desired location.


Well, not really. The file was duly generated, but the filename was not returned by Project.render method. But it was a bug of course. I've fixed it and pushed to movie branch.
Problem is I mixed the patch with a few other updates enabling batch mode for all renderers.
So I'm gonna terminate my on-going work and notice you when I am finished, so that you can merge.


In Blender, the default option is to save the images or the video in a temporary folder, but the user can change it to a folder of his choice


This is the same in Render: you can specify the destination file, this is the Output Image parameter of the Project. If you specify this file and you change it from one rendering to another, you won't overwrite.

**Comment by howetuft** [comment]
Hello,
Along with the new features exposed in forum (https://forum.freecadweb.org/viewtopic.php?f=3&t=55297&p=649981#p649981), I've also fixed the above bug.
So you can merge this PR, if you please!

**Pull request merged**
